//-----------------------------------------------------------------------------
//  Copyright (C) 2026, Gene Bushuyev
//
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#include <string>
#include <thread>
#include <vector>
#include <atomic>
#include <stdexcept>
#include "../include/axe.h"
#include <yadro/util/gbtest.h>

namespace
{
    using namespace gb::yadro::util;
    using I = const char*;

    // parse the whole string with the rule, returns true if matched
    template<class R>
    bool match_all(const R& r, const std::string& str)
    {
        auto res = axe::parse(std::ref(r), str.c_str(), str.c_str() + str.size());
        return res.matched && res.position == str.c_str() + str.size();
    }

    std::string parens(size_t n) { return std::string(n, '(') + std::string(n, ')'); }

    GB_TEST(axe, test_depth_limit)
    {
        // ')' is tested before recursion, so the nested rule is invoked only for '('
        axe::r_rule<I> paren;
        paren = axe::r_depth_limit('(' & (axe::r_char(')') | std::ref(paren) & ')'), 3);

        gbassert(match_all(paren, parens(1)));
        gbassert(match_all(paren, parens(3)));

        // the fourth nested invocation throws, the position points at the fourth '('
        std::string deep = parens(4);
        bool thrown = false;
        try
        {
            axe::parse(std::ref(paren), deep.c_str(), deep.c_str() + deep.size());
        }
        catch (const axe::depth_limit_exceeded<I>& ex)
        {
            thrown = true;
            gbassert(ex.max_depth() == 3);
            gbassert(ex.position() == deep.c_str() + 3);
            gbassert(std::string(ex.what()).find("limit of 3") != std::string::npos);
        }
        gbassert(thrown);
        gbassert(axe::detail::depth_frames() == nullptr);

        // depth_limit_exceeded is also a failure
        thrown = false;
        try
        {
            axe::parse(std::ref(paren), deep.c_str(), deep.c_str() + deep.size());
        }
        catch (const axe::failure<char>&)
        {
            thrown = true;
        }
        gbassert(thrown);

        // the counter was restored by unwinding
        gbassert(match_all(paren, parens(3)));
        gbassert(axe::detail::depth_frames() == nullptr);

        // zero limit rejects any invocation
        auto never = axe::r_depth_limit(axe::r_char('x'), 0);
        gbassert(never.max_depth() == 0);
        thrown = false;
        std::string x = "x";
        try { axe::parse(never, x); }
        catch (const axe::depth_limit_exceeded<std::string::iterator>&) { thrown = true; }
        gbassert(thrown);

        // sequential (non-nested) invocations don't accumulate depth
        auto once = axe::r_depth_limit(axe::r_char('x'), 1);
        gbassert(match_all(*once, std::string(100, 'x')));

        // every invocation counts, including an attempt that wouldn't match:
        // this grammar tries one more nested level than it matches
        axe::r_rule<I> probing;
        probing = axe::r_depth_limit('(' & ~std::ref(probing) & ')', 3);
        gbassert(match_all(probing, parens(2)));
        thrown = false;
        std::string three = parens(3);
        try { match_all(probing, three); }
        catch (const axe::depth_limit_exceeded<I>& ex) { thrown = ex.position() == three.c_str() + 3; }
        gbassert(thrown);
    }

    GB_TEST(axe, test_depth_limit_reentrant)
    {
        // a semantic action starts a nested parse with the same rule object on the same thread:
        // nested invocations are counted cumulatively
        axe::r_rule<I> rule;
        int nested = 0;
        int max_nested = 0;
        const std::string x = "x";
        rule = axe::r_depth_limit(axe::r_char('x') >> [&](auto, auto)
        {
            if (nested < max_nested)
            {
                ++nested;
                axe::parse(std::ref(rule), x.c_str(), x.c_str() + 1);
            }
        }, 3);

        max_nested = 2; // total depth 3
        gbassert(match_all(rule, x));
        gbassert(nested == 2);

        nested = 0;
        max_nested = 3; // total depth 4
        bool thrown = false;
        try { match_all(rule, x); }
        catch (const axe::depth_limit_exceeded<I>& ex) { thrown = true; gbassert(ex.max_depth() == 3); }
        gbassert(thrown);
        gbassert(axe::detail::depth_frames() == nullptr);

        nested = 0;
        max_nested = 2;
        gbassert(match_all(rule, x));

        // an exception thrown from a semantic action inside nested invocations restores the depth
        axe::r_rule<I> paren;
        auto close = axe::r_char(')') >> [](auto i1, auto)
        {
            if (i1[1] == '!')
                throw std::runtime_error("action failed");
        };
        paren = axe::r_depth_limit('(' & (close | std::ref(paren) & close), 5);

        thrown = false;
        try { match_all(paren, "((()!))"); }
        catch (const std::runtime_error&) { thrown = true; }
        gbassert(thrown);
        gbassert(axe::detail::depth_frames() == nullptr);
        gbassert(match_all(paren, parens(5)));
        gbassert(!match_all(paren, parens(5) + ")"));
    }

    GB_TEST(axe, test_depth_limit_distinct_rules)
    {
        // mutually recursive rules with separate limits are counted separately
        axe::r_rule<I> a, b;
        a = axe::r_depth_limit('[' & (axe::r_char(']') | std::ref(b) & ']'), 2);
        b = axe::r_depth_limit('(' & (axe::r_char(')') | std::ref(a) & ')'), 2);

        gbassert(match_all(a, "[([()])]"));

        bool thrown = false;
        try { match_all(a, "[([([])])]"); }
        catch (const axe::depth_limit_exceeded<I>& ex) { thrown = true; gbassert(ex.max_depth() == 2); }
        gbassert(thrown);
        gbassert(axe::detail::depth_frames() == nullptr);

        // b is entered three times
        thrown = false;
        try { match_all(b, "([([()])])"); }
        catch (const axe::depth_limit_exceeded<I>&) { thrown = true; }
        gbassert(thrown);
        gbassert(axe::detail::depth_frames() == nullptr);
    }

    // parse must throw depth_limit_exceeded with max_depth and position at offset from the start
    template<class R>
    bool throws_depth_limit(const R& r, const std::string& str, size_t max_depth, size_t offset)
    {
        try
        {
            axe::parse(std::ref(r), str.c_str(), str.c_str() + str.size());
        }
        catch (const axe::depth_limit_exceeded<I>& ex)
        {
            return ex.max_depth() == max_depth && ex.position() == str.c_str() + offset
                && axe::detail::depth_frames() == nullptr;
        }
        return false;
    }

    GB_TEST(axe, test_depth_limit_nested_or)
    {
        // the wrapper is an alternative of r_or_t, which is what r_rule holds,
        // the depth must be counted on the same wrapper object in every invocation
        axe::r_rule<I> value;
        auto array = '[' & (axe::r_char(']') | std::ref(value) & ']');
        value = axe::r_char('1') | axe::r_depth_limit(array, 3);

        gbassert(match_all(value, "1"));
        gbassert(match_all(value, "[1]"));
        gbassert(match_all(value, "[[[1]]]"));
        gbassert(match_all(value, "[[[]]]"));
        gbassert(throws_depth_limit(value, "[[[[1]]]]", 3, 3));
        gbassert(throws_depth_limit(value, "[[[[]]]]", 3, 3));

        // hostile input must be rejected by the limit, not by overflowing the stack
        gbassert(throws_depth_limit(value, std::string(1'000'000, '['), 3, 3));
        gbassert(match_all(value, "[[[1]]]"));
    }

    GB_TEST(axe, test_depth_limit_nested_and)
    {
        // the wrapper is an operand of r_and_t, which is what r_rule holds
        axe::r_rule<I> list;
        list = '(' & axe::r_depth_limit(axe::r_char(')') | std::ref(list) & ')', 4);

        gbassert(match_all(list, parens(1)));
        gbassert(match_all(list, parens(4)));
        gbassert(!match_all(list, parens(4) + ")"));
        gbassert(throws_depth_limit(list, parens(5), 4, 5)); // '(' is consumed before the wrapper
        gbassert(throws_depth_limit(list, std::string(1'000'000, '('), 4, 5));
        gbassert(match_all(list, parens(4)));

        // the wrapper nested in both: r_or_t inside r_and_t inside r_or_t
        axe::r_rule<I> value;
        value = axe::r_char('1') | '[' & (axe::r_char(']') | axe::r_depth_limit(std::ref(value), 2) & ']');

        gbassert(match_all(value, "[[1]]"));
        gbassert(match_all(value, "[[[]]]"));
        gbassert(throws_depth_limit(value, "[[[1]]]", 2, 3));
        gbassert(throws_depth_limit(value, std::string(1'000'000, '['), 2, 3));
    }

    GB_TEST(axe, test_depth_limit_threads)
    {
        // the same rule object is used concurrently from several threads,
        // a shared counter would reject valid input or accept too deep input
        axe::r_rule<I> paren;
        paren = axe::r_depth_limit('(' & (axe::r_char(')') | std::ref(paren) & ')'), 50);

        const std::string ok = parens(50);
        const std::string deep = parens(51);
        std::atomic<int> errors{ 0 };
        std::atomic<bool> go{ false };

        std::vector<std::thread> threads;
        for (int t = 0; t < 8; ++t)
        {
            threads.emplace_back([&, t]
            {
                while (!go)
                    std::this_thread::yield();

                for (int n = 0; n < 2000; ++n)
                {
                    const bool valid = (n + t) % 2 != 0;
                    try
                    {
                        if (match_all(paren, valid ? ok : deep) != valid)
                            ++errors;
                        if (!valid)
                            ++errors; // too deep input must throw
                    }
                    catch (const axe::depth_limit_exceeded<I>&)
                    {
                        if (valid)
                            ++errors;
                    }
                }

                if (axe::detail::depth_frames() != nullptr)
                    ++errors;
            });
        }
        go = true;
        for (auto& t : threads)
            t.join();

        gbassert(errors == 0);
    }

    GB_TEST(axe, test_depth_limit_parse_tree)
    {
        using namespace axe::shortcuts;
        // extracting rules keep their parse tree data when wrapped
        auto rule = axe::r_depth_limit(*(_d & ','), 1);
        std::string str = "1,2,3,";
        auto res = axe::parse_tree(rule, str);
        gbassert(res.matched);
        gbassert(res.data.size() == 3);
        gbassert(axe::get_as<std::string>(std::get<0>(res.data[2])) == "3");

        auto limited = axe::r_depth_limit(*(_d & ','), 0);
        bool thrown = false;
        try { axe::parse_tree(limited, str); }
        catch (const axe::depth_limit_exceeded<std::string::iterator>&) { thrown = true; }
        gbassert(thrown);
    }
}
