//-----------------------------------------------------------------------------
//  Copyright (C) 2011-2022, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#include <string>
#include <map>
#include <vector>
#include <sstream>
#pragma warning(disable:4503)
#include "../include/axe.h"
#include <yadro/util/gbtest.h>

template<class I>
auto parse_json(I begin, I end, size_t max_depth = 16)
{
    using namespace axe::shortcuts;
    std::ostringstream ss;

    auto json_hex = axe::r_many(axe::r_hex(), 4);
    // \uXXXX escape: UTF-16 surrogates are only valid as a high-low pair (RFC 8259, section 7)
    auto json_high = axe::r_any("dD") & axe::r_any("89abAB") & _x & _x;
    auto json_low = axe::r_any("dD") & axe::r_any("cdefCDEF") & _x & _x;
    auto json_surrogate = axe::r_any("dD") & axe::r_any("89abcdefABCDEF");
    auto json_unicode = 'u' & (json_high & "\\u"_axe & json_low | !json_surrogate & json_hex);
    auto json_escaped = "\""_axe | '\\' | '/' | 'b' | 'f'
        | 'n' | 'r' | 't' | json_unicode;
    // unescaped characters must be well-formed UTF-8 and not control characters
    auto json_control = axe::r_any('\x00', '\x1f');
    auto json_char = axe::r_utf8() - '"' - '\\' - json_control | '\\' & json_escaped;
    auto json_string = '"' & *json_char & '"';
    // definition of json_value requires recursion
    // neither 'auto' declation, nor lambda functions allow recursion
    // instead one can create function object with recursion in operator()
    // or use polymorphic r_rule class, which performs type erasure
    axe::r_rule<I> json_value;
    // json_value must be wrapped with std::ref because rules are taken by value
    // an empty array is checked first, so no nested value is attempted for "[]"
    auto json_array = *_ws & '[' & *_ws
        & (']'_axe | (*_ws & std::ref(json_value) & *_ws) % ',' & ']');

    auto json_record = *_ws & json_string & *_ws
        & ':' & *_ws & std::ref(json_value) & *_ws;

    auto json_object = *_ws & '{' & ~(json_record % ',') & *_ws & '}';

    // r_depth_limit bounds the recursion, so deeply nested input can't overflow the stack;
    // every nested value passes through this single wrapper object, the top level value has depth 1;
    // each level of this grammar takes about 40 KB of stack in MSVC debug build with /ZI /JMC
    // and about 3 KB in release build,
    // the limit must fit the stack of the parsing thread
    json_value = axe::r_depth_limit(json_string | _double | json_object | json_array
        | "true" | "false" | "null", max_depth);

    try
    {
        parse((*_ws & std::ref(json_value) & *_ws) >> [&](auto i1, auto i2)
        {
            ss << "JSON parsed:" << std::string(i1, i2);
        } & _z
            | axe::r_fail([&](auto i1, auto i2, auto i3)
        {
            ss << "parsing failed at place pointed by !\n"
                << std::string(i1, i2) << '!' << std::string(i2, i3);
        }), begin, end);
    }
    catch (const axe::depth_limit_exceeded<I>& ex)
    {
        ss << "nesting too deep (limit " << ex.max_depth() << ") at offset "
            << std::distance(begin, ex.position());
    }

    return ss.str();
}

void _test_json()
{
    std::cout << "--------------------------------------------------------test_json:\n";
    std::string str(R"*(
{
"category": 1,
"sub-category": 1.1,
"name": "inventory",
"tags": ["warehouse","inventory"],
"vehicles" :
[
        {
        "id": 123456789,
        "make": "Honda",
        "model": "Ridgeline",
        "trim": "RTL",
        "price": 32616,
        "tags": ["truck","V6","4WD"]
        },
        {
        "id": 748201836,
        "make": "Honda",
        "model": "Pilot",
        "trim": "Touring",
        "price": 38042,
        "tags": ["SUV","V6","4WD"]
        }
]
})*");

    parse_json(str.begin(), str.end());
    std::cout << "\n-----------------------------------------------------------------\n";
}

namespace
{
    using namespace gb::yadro::util;

    GB_TEST(axe, test_json)
    {
        std::string str(R"*(
{
"category": 1,
"sub-category": 1.1,
"name": "inventory",
"tags": ["warehouse","inventory"],
"vehicles" :
[
        {
        "id": 123456789,
        "make": "Honda",
        "model": "Ridgeline",
        "trim": "RTL",
        "price": 32616,
        "tags": ["truck","V6","4WD"]
        },
        {
        "id": 748201836,
        "make": "Honda",
        "model": "Pilot",
        "trim": "Touring",
        "price": 38042,
        "tags": ["SUV","V6","4WD"]
        }
]
})*");

        auto res = parse_json(str.begin(), str.end());
        auto golden = R"*(JSON parsed:
{
"category": 1,
"sub-category": 1.1,
"name": "inventory",
"tags": ["warehouse","inventory"],
"vehicles" :
[
        {
        "id": 123456789,
        "make": "Honda",
        "model": "Ridgeline",
        "trim": "RTL",
        "price": 32616,
        "tags": ["truck","V6","4WD"]
        },
        {
        "id": 748201836,
        "make": "Honda",
        "model": "Pilot",
        "trim": "Touring",
        "price": 38042,
        "tags": ["SUV","V6","4WD"]
        }
]
})*";
        gbassert(res == golden);
    }

    bool json_ok(const std::string& str, size_t max_depth = 16)
    {
        return parse_json(str.begin(), str.end(), max_depth).rfind("JSON parsed:", 0) == 0;
    }

    GB_TEST(axe, test_json_valid)
    {
        gbassert(json_ok("{}"));
        gbassert(json_ok("[]"));
        gbassert(json_ok(R"( { "a" : [ ] , "b" : { } } )"));
        gbassert(json_ok("\"scalar\""));
        // surrogate pair (U+1F600), either case, and BMP escapes
        gbassert(json_ok(R"(["\ud83d\ude00"])"));
        gbassert(json_ok(R"(["\uD83D\uDE00"])"));
        gbassert(json_ok(R"(["\u00e9\u20AC\u0000\uffff"])"));
        gbassert(json_ok(R"(["\"\\\/\b\f\n\r\t"])"));
        // raw multi-byte UTF-8: U+00E9, U+20AC, U+1F600, and U+10FFFF
        gbassert(json_ok("[\"\xC3\xA9" "\xE2\x82\xAC" "\xF0\x9F\x98\x80" "\xF4\x8F\xBF\xBF\"]"));
        // DEL is not a control character in JSON
        gbassert(json_ok("[\"\x7f\"]"));
    }

    GB_TEST(axe, test_json_invalid)
    {
        // raw control characters are not allowed in strings
        gbassert(!json_ok("[\"a\tb\"]"));
        gbassert(!json_ok("[\"a\nb\"]"));
        gbassert(!json_ok(std::string("[\"a\0b\"]", 7)));
        gbassert(!json_ok("[\"\x1f\"]"));
        // lone high surrogate, high surrogate followed by non-surrogate, lone low surrogate
        gbassert(!json_ok(R"(["\ud83d"])"));
        gbassert(!json_ok(R"(["\ud83dx"])"));
        gbassert(!json_ok(R"(["\ud83d\u0041"])"));
        gbassert(!json_ok(R"(["\ud83d\ud83d"])"));
        gbassert(!json_ok(R"(["\ude00"])"));
        gbassert(!json_ok(R"(["\ude00\ud83d"])"));
        // invalid UTF-8: stray continuation, overlong, encoded surrogate, above U+10FFFF, truncated
        gbassert(!json_ok("[\"\x80\"]"));
        gbassert(!json_ok("[\"\xC0\xAF\"]"));
        gbassert(!json_ok("[\"\xE0\x80\xAF\"]"));
        gbassert(!json_ok("[\"\xED\xA0\x80\"]"));
        gbassert(!json_ok("[\"\xF4\x90\x80\x80\"]"));
        gbassert(!json_ok("[\"\xE2\x82\"]"));
        gbassert(!json_ok("[\"\xFF\"]"));
        // malformed structure
        gbassert(!json_ok("[1,]"));
        gbassert(!json_ok("{\"a\"}"));
    }

    GB_TEST(axe, test_json_depth)
    {
        // limit 16: 16 nested arrays are accepted, 17 are rejected
        gbassert(json_ok(std::string(16, '[') + std::string(16, ']')));
        std::string deep = std::string(17, '[') + std::string(17, ']');
        auto res = parse_json(deep.begin(), deep.end());
        gbassert(res == "nesting too deep (limit 16) at offset 16");

        // a deeply nested hostile input doesn't overflow the stack
        std::string hostile(100000, '[');
        res = parse_json(hostile.begin(), hostile.end());
        gbassert(res == "nesting too deep (limit 16) at offset 16");

        // mixed objects and arrays count against the same limit
        std::string mixed;
        for (int i = 0; i < 40; ++i)
            mixed += "{\"a\":[";
        res = parse_json(mixed.begin(), mixed.end());
        gbassert(res.rfind("nesting too deep (limit 16)", 0) == 0);

        // the parser is usable after the exception
        gbassert(json_ok("[[[1]]]", 4));
        gbassert(!json_ok("[[[[1]]]]", 4));
    }
}