//-----------------------------------------------------------------------------
//  Copyright (C) 2026, Gene Bushuyev
//
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#include <string>
#include <vector>
#include <initializer_list>
#include "../include/axe.h"
#include <yadro/util/gbtest.h>

namespace
{
    using namespace gb::yadro::util;

    // returns the number of code units matched by one r_utf8, or -1 on mismatch
    template<class C>
    int utf8_len(const std::vector<C>& v)
    {
        auto res = axe::r_utf8()(v.data(), v.data() + v.size());
        if (!res.matched)
            return res.position == v.data() ? -1 : -2; // failure must not advance
        return int(res.position - v.data());
    }

    template<class C>
    std::vector<C> bytes(std::initializer_list<unsigned> list)
    {
        std::vector<C> v;
        for (auto b : list)
            v.push_back(static_cast<C>(b));
        return v;
    }

    template<class C>
    void test_utf8_code_units()
    {
        // well-formed: boundaries of each sequence length and around the surrogate range
        gbassert(utf8_len(bytes<C>({ 0x00 })) == 1);
        gbassert(utf8_len(bytes<C>({ 0x41, 0x42 })) == 1);
        gbassert(utf8_len(bytes<C>({ 0x7F })) == 1);
        gbassert(utf8_len(bytes<C>({ 0xC2, 0x80 })) == 2);             // U+0080
        gbassert(utf8_len(bytes<C>({ 0xDF, 0xBF })) == 2);             // U+07FF
        gbassert(utf8_len(bytes<C>({ 0xE0, 0xA0, 0x80 })) == 3);       // U+0800
        gbassert(utf8_len(bytes<C>({ 0xED, 0x9F, 0xBF })) == 3);       // U+D7FF
        gbassert(utf8_len(bytes<C>({ 0xEE, 0x80, 0x80 })) == 3);       // U+E000
        gbassert(utf8_len(bytes<C>({ 0xEF, 0xBF, 0xBF, 0x41 })) == 3); // U+FFFF
        gbassert(utf8_len(bytes<C>({ 0xF0, 0x90, 0x80, 0x80 })) == 4); // U+10000
        gbassert(utf8_len(bytes<C>({ 0xF0, 0x9F, 0x98, 0x80 })) == 4); // U+1F600
        gbassert(utf8_len(bytes<C>({ 0xF4, 0x8F, 0xBF, 0xBF })) == 4); // U+10FFFF

        // ill-formed: empty input, stray continuation bytes
        gbassert(utf8_len(bytes<C>({})) == -1);
        gbassert(utf8_len(bytes<C>({ 0x80 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xBF, 0x41 })) == -1);
        // overlong encodings
        gbassert(utf8_len(bytes<C>({ 0xC0, 0x80 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xC1, 0xBF })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xE0, 0x80, 0x80 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xE0, 0x9F, 0xBF })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xF0, 0x80, 0x80, 0x80 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xF0, 0x8F, 0xBF, 0xBF })) == -1);
        // surrogates U+D800..U+DFFF encoded directly
        gbassert(utf8_len(bytes<C>({ 0xED, 0xA0, 0x80 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xED, 0xBF, 0xBF })) == -1);
        // code points above U+10FFFF and invalid lead bytes
        gbassert(utf8_len(bytes<C>({ 0xF4, 0x90, 0x80, 0x80 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xF5, 0x80, 0x80, 0x80 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xF8, 0x88, 0x80, 0x80, 0x80 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xFE })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xFF })) == -1);
        // truncated sequences
        gbassert(utf8_len(bytes<C>({ 0xC3 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xE2, 0x82 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xF0, 0x9F, 0x98 })) == -1);
        // continuation byte replaced by other bytes
        gbassert(utf8_len(bytes<C>({ 0xC3, 0x41 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xE2, 0x82, 0xC0 })) == -1);
        gbassert(utf8_len(bytes<C>({ 0xF0, 0x9F, 0x98, 0x20 })) == -1);
    }

    GB_TEST(axe, test_utf8)
    {
        test_utf8_code_units<char>();
        test_utf8_code_units<unsigned char>();
        test_utf8_code_units<signed char>();
        test_utf8_code_units<char8_t>();
    }

    GB_TEST(axe, test_utf8_rules)
    {
        using namespace axe::shortcuts;

        // whole input validation with char8_t, char, and unsigned char iterators
        std::u8string u8 = u8"a\u00e9\u20ac\U0001F600z";
        gbassert(axe::parse(*axe::r_utf8() & _z, u8).matched);
        gbassert(axe::parse(axe::r_utf8() * 5 & _z, u8).matched);
        std::string s(u8.begin(), u8.end());
        gbassert(axe::parse(*axe::r_utf8() & _z, s).matched);
        std::vector<unsigned char> uc(u8.begin(), u8.end());
        gbassert(axe::parse(*axe::r_utf8() & _z, uc).matched);

        uc.insert(uc.begin() + 3, 0xC0);
        gbassert(!axe::parse(*axe::r_utf8() & _z, uc).matched);

        // string form matches the longest well-formed prefix
        std::string mixed = "ab\xC3\xA9" "\xED\xA0\x80" "cd";
        auto res = axe::parse(axe::r_utf8str(), mixed);
        gbassert(res.matched && res.position == mixed.begin() + 4);
        std::string stray = "\x80";
        gbassert(!axe::parse(axe::r_utf8str(), stray).matched);
        std::string empty;
        gbassert(!axe::parse(axe::r_utf8str(), empty).matched);
        gbassert(axe::parse(axe::r_utf8str() & _z, u8).matched);

        // failure position is the start of the ill-formed sequence
        std::string bad = "\xE2\x82";
        auto r1 = axe::parse(axe::r_utf8(), bad);
        gbassert(!r1.matched && r1.position == bad.begin());

        // composes with other rules: any code point except a quote
        auto no_quote = +(axe::r_utf8() - '"');
        std::string q = "\xC3\xA9\"";
        auto r2 = axe::parse(no_quote, q);
        gbassert(r2.matched && r2.position == q.begin() + 2);

        gbassert(std::string(axe::get_name(axe::r_utf8())) == "r_utf8");
        gbassert(std::string(axe::get_name(axe::r_utf8str())) == "r_utf8str");
    }
}

