//-----------------------------------------------------------------------------
//  Copyright (C) 2026, Gene Bushuyev
//
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

#include <stddef.h>
#include <utility>
#include "axe_result.h"
#include "axe_iterator.h"
#include "axe_exception.h"
#include "axe_composite.h"
#include "axe_detail.h"

namespace axe
{
    namespace detail
    {
        //-------------------------------------------------------------------------
        /// depth_frame holds the current nesting depth of one depth limited rule object
        /// frames of the rules active on a thread form a stack linked through next
        //-------------------------------------------------------------------------
        struct depth_frame
        {
            const void* key;
            size_t depth;
            depth_frame* next;
        };

        //-------------------------------------------------------------------------
        /// top of the per-thread stack of depth frames
        //-------------------------------------------------------------------------
        inline depth_frame*& depth_frames() noexcept
        {
            static thread_local depth_frame* top = nullptr;
            return top;
        }

        //-------------------------------------------------------------------------
        /// depth_guard increments the depth of the rule identified by key on construction
        /// and decrements it on destruction (including stack unwinding)
        /// the outermost invocation of a rule on a thread owns the frame, nested ones share it,
        /// so the lookup cost is proportional to the number of distinct limited rules
        /// currently active on the thread, not to the nesting depth
        //-------------------------------------------------------------------------
        class depth_guard
        {
            depth_frame own_{};
            depth_frame* frame_;
        public:
            explicit depth_guard(const void* key) noexcept : frame_(depth_frames())
            {
                while (frame_ && frame_->key != key)
                    frame_ = frame_->next;

                if (frame_)
                {
                    ++frame_->depth;
                }
                else
                {
                    depth_frame*& top = depth_frames();
                    own_ = depth_frame{ key, 1, top };
                    frame_ = top = &own_;
                }
            }

            ~depth_guard()
            {
                if (frame_ == &own_)
                    depth_frames() = own_.next;
                else
                    --frame_->depth;
            }

            depth_guard(const depth_guard&) = delete;
            depth_guard& operator= (const depth_guard&) = delete;

            size_t depth() const noexcept { return frame_->depth; }
        };
    }

    //-----------------------------------------------------------------------------
    /// r_depth_limit_t limits the nesting depth of the wrapped rule
    /// each invocation increments the depth for the duration of the match,
    /// if the depth exceeds max_depth, depth_limit_exceeded<Iterator> is thrown
    /// before the wrapped rule is invoked
    /// the depth is counted per wrapper object and per thread, so the same rule object
    /// can be used by several threads concurrently and nested parses on one thread
    /// are counted cumulatively; the count is restored when an exception propagates
    /// copies of the wrapper count separately; a parse must not be suspended
    /// (fiber or coroutine switch) while inside the wrapper
    //-----------------------------------------------------------------------------
    template<class R>
    class r_depth_limit_t final
    {
        R r_;
        size_t max_depth_;
    public:
        template<class T>
        r_depth_limit_t(T&& r, size_t max_depth) : r_(std::forward<T>(r)), max_depth_(max_depth) {}

        size_t max_depth() const noexcept { return max_depth_; }

        template<class Iterator, class Iterator2>
        result<Iterator> operator() (Iterator i1, Iterator2 i2) const
        {
            detail::depth_guard guard(this);
            if (guard.depth() > max_depth_)
                throw depth_limit_exceeded<Iterator>(max_depth_, i1, i2);
            return r_(i1, i2);
        }

        template<class Iterator>
        auto operator() (it_pair<Iterator> itp) const -> detail::parse_tree_result_t<const R&, Iterator>
        {
            detail::depth_guard guard(this);
            if (guard.depth() > max_depth_)
                throw depth_limit_exceeded<Iterator>(max_depth_, itp.begin(), itp.end());
            return detail::parse_tree_invoke(r_, itp);
        }

        const char* name() const { return "r_depth_limit"; }
    };

    template<class R>
    r_depth_limit_t(R&&, size_t)->r_depth_limit_t<std::decay_t<R>>;

    //-----------------------------------------------------------------------------
    /// function r_depth_limit wraps rule r to limit its nesting depth to max_depth
    /// on violation depth_limit_exceeded<Iterator> exception is thrown
    /// typical use is on the right hand side of a recursive r_rule definition:
    ///     r_rule<I> value;
    ///     value = r_depth_limit(... std::ref(value) ..., 256);
    /// the limit counts nested invocations of this wrapper object, the outermost
    /// invocation has depth 1; every invocation counts, including one that fails to match,
    /// so a grammar like '(' & ~r & ')' invokes r one level deeper than it matches,
    /// while '(' & (r_char(')') | r & ')') doesn't
    /// stack usage per level depends on the grammar and build, choose max_depth so
    /// that max_depth levels fit the stack of the parsing thread
    //-----------------------------------------------------------------------------
    template<class R>
    inline
        r_depth_limit_t<detail::enable_if_rule<R>>
        r_depth_limit(R&& r, size_t max_depth)
    {
        return r_depth_limit_t<std::decay_t<R>>(std::forward<R>(r), max_depth);
    }
}
