//-----------------------------------------------------------------------------
//  Copyright (C) 2011-2022, Gene Bushuyev
//  
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

//-----------------------------
// check compiler support
#if defined( _MSC_VER) 
    #if _MSC_VER < 1914
    #error Visual C++ 2017 or later required
    #endif
#elif __cplusplus < 201703L
    #error c++ 17 compiler required
#endif

//-----------------------------
#define AXE_IS_RULE(...) axe::is_rule_v<std::remove_reference_t<__VA_ARGS__>>
#define AXE_IS_PREDICATE(...) axe::is_predicate_v<std::remove_reference_t<__VA_ARGS__>>

// ATTN: these macros are deprecated, will be removed later
// macros for backward compatibility with v.1
#define AXE_RULE : axe::r_base
#define AXE_EXTRACTOR : axe::e_base
#define AXE_PREDICATE : axe::p_base
