//-----------------------------------------------------------------------------
//  Copyright (C) 2026, Gene Bushuyev
//
//  Boost Software License - Version 1.0 - August 17th, 2003
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------

#pragma once

#include <type_traits>
#include <iterator>
#include "axe_result.h"
#include "axe_trait.h"

namespace axe
{
    namespace detail
    {
        //-------------------------------------------------------------------------
        /// utf8_advance advances i past one well-formed UTF-8 encoded code point
        /// (RFC 3629, Unicode Table 3-7) and returns true,
        /// returns false and leaves i unchanged if the sequence at i is ill-formed:
        /// stray continuation byte, overlong encoding, surrogate code point (U+D800..U+DFFF),
        /// code point above U+10FFFF, bytes 0xC0, 0xC1, 0xF5..0xFF, or truncated sequence
        /// a forward iterator is required: the sequence is examined through a copy of i,
        /// which would move a single-pass iterator (e.g. std::istreambuf_iterator)
        //-------------------------------------------------------------------------
        template<class Iterator, class Iterator2>
        bool utf8_advance(Iterator& i, Iterator2 end)
        {
            static_assert(is_forward_iterator<Iterator>,
                "UTF-8 rules require forward iterators, single-pass input iterators can't restore the position");
            using value_t = std::remove_cv_t<std::remove_reference_t<decltype(*i)>>;
            static_assert(std::is_integral_v<value_t> && sizeof(value_t) == 1,
                "UTF-8 rules require iterators over 8-bit code units (char, char8_t, unsigned char)");

            if (i == end)
                return false;

            const unsigned b0 = static_cast<unsigned char>(*i);
            if (b0 < 0x80)
            {
                ++i;
                return true;
            }

            // number of continuation bytes and valid range of the first continuation byte
            unsigned n = 0, lo = 0x80, hi = 0xBF;
            if (b0 >= 0xC2 && b0 <= 0xDF)
                n = 1;
            else if (b0 == 0xE0)
                n = 2, lo = 0xA0;       // exclude overlong
            else if (b0 == 0xED)
                n = 2, hi = 0x9F;       // exclude surrogates U+D800..U+DFFF
            else if (b0 >= 0xE1 && b0 <= 0xEF)
                n = 2;
            else if (b0 == 0xF0)
                n = 3, lo = 0x90;       // exclude overlong
            else if (b0 == 0xF4)
                n = 3, hi = 0x8F;       // exclude code points above U+10FFFF
            else if (b0 >= 0xF1 && b0 <= 0xF3)
                n = 3;
            else
                return false;           // continuation byte, 0xC0, 0xC1, 0xF5..0xFF

            Iterator j = i;
            ++j;
            for (unsigned k = 0; k < n; ++k, ++j, lo = 0x80, hi = 0xBF)
            {
                if (j == end)
                    return false;
                const unsigned b = static_cast<unsigned char>(*j);
                if (b < lo || b > hi)
                    return false;
            }

            i = j;
            return true;
        }
    }

    //-------------------------------------------------------------------------
    /// r_utf8_t matches exactly one well-formed UTF-8 encoded code point
    /// ill-formed sequences don't match (see detail::utf8_advance),
    /// on failure the returned position is the start of the sequence
    /// works with forward iterators over char, signed char, unsigned char, and char8_t;
    /// single-pass input iterators are rejected at compile time (the rule isn't invocable),
    /// because the start position of a rejected sequence can't be restored for them
    //-------------------------------------------------------------------------
    struct r_utf8_t final
    {
        template<class Iterator, class Iterator2>
        auto operator() (Iterator i1, Iterator2 i2) const
            -> std::enable_if_t<is_forward_iterator<Iterator>, result<Iterator>>
        {
            Iterator i = i1;
            return detail::utf8_advance(i, i2) ? result(true, i) : result(false, i1);
        }

        const char* name() const { return "r_utf8"; }
    };

    //-------------------------------------------------------------------------
    /// r_utf8str_t matches one or more well-formed UTF-8 encoded code points,
    /// matching stops before the first ill-formed sequence or at the end of input
    /// to validate that the whole input is UTF-8 use: *r_utf8() & r_end()
    /// like r_utf8_t, it requires forward iterators
    //-------------------------------------------------------------------------
    struct r_utf8str_t final
    {
        template<class Iterator, class Iterator2>
        auto operator() (Iterator i1, Iterator2 i2) const
            -> std::enable_if_t<is_forward_iterator<Iterator>, result<Iterator>>
        {
            Iterator i = i1;
            while (detail::utf8_advance(i, i2)) {}
            return make_result(i != i1, i);
        }

        const char* name() const { return "r_utf8str"; }
    };

    //-------------------------------------------------------------------------
    /// function r_utf8 creates a rule matching one well-formed UTF-8 code point
    //-------------------------------------------------------------------------
    inline r_utf8_t r_utf8() { return r_utf8_t{}; }

    //-------------------------------------------------------------------------
    /// function r_utf8str creates a rule matching one or more well-formed UTF-8 code points
    //-------------------------------------------------------------------------
    inline r_utf8str_t r_utf8str() { return r_utf8str_t{}; }
}
